version: "3"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ecut@2025
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
  back:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
    volumes:
      - ./data:/APP/dist/data
